behaviors:
  Dog:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256           # kleiner, damit pro Training-Update weniger RAM benötigt wird
      buffer_size: 4096         # reduziert von 10240 → schnellerer Durchsatz, weniger Speicher
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 500000   # alle 500k Steps Checkpoints speichern
    max_steps: 20000000
    time_horizon: 128              # leicht höher, damit längere Episodenverläufe berücksichtigt werden
    summary_freq: 100000           # weniger Logging → RAM-Schonung
